El módulo de "Explotación" falló en,list indices must be integers or slices, not str:tipo,<class 'TypeError'>:archivo,app.py:linea,377
